// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3VC82b2O-FhdQSw2qzIiEKLKevGMiHI',
    appId: '1:406911156307:web:1529003f4fd47bac2406a6',
    messagingSenderId: '406911156307',
    projectId: 'habitflow-485ab',
    authDomain: 'habitflow-485ab.firebaseapp.com',
    storageBucket: 'habitflow-485ab.firebasestorage.app',
    measurementId: 'G-QVX2SDHCXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY4nI3XliGYXG5QGaAzzLII5ePGUp_yT4',
    appId: '1:406911156307:android:3221a441179961f82406a6',
    messagingSenderId: '406911156307',
    projectId: 'habitflow-485ab',
    storageBucket: 'habitflow-485ab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3VC82b2O-FhdQSw2qzIiEKLKevGMiHI',
    appId: '1:406911156307:web:d7f90c2310ac506e2406a6',
    messagingSenderId: '406911156307',
    projectId: 'habitflow-485ab',
    authDomain: 'habitflow-485ab.firebaseapp.com',
    storageBucket: 'habitflow-485ab.firebasestorage.app',
    measurementId: 'G-XYMEQL4MKG',
  );

}